version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  apache:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./apache-config:/usr/local/apache2/conf
    depends_on:
      - web
